/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view.menu;

import br.com.view.funcionario.*;
import br.com.view.Principal;

/**
 *
 * @author Felip
 */
public class PnMenuFuncionario extends javax.swing.JPanel {
    private java.awt.Component panelAtivo;
    /**
     * Creates new form PnMenuFuncionario
     */
    public PnMenuFuncionario() {
        initComponents();
        ativarPanel(pnEmprestimo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        pnCadastrarLivro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnEmprestimo = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pnRanking = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        menu.setBackground(new java.awt.Color(59, 58, 149));

        pnCadastrarLivro.setBackground(new java.awt.Color(59, 58, 149));
        pnCadastrarLivro.setPreferredSize(new java.awt.Dimension(162, 60));
        pnCadastrarLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnCadastrarLivrobtGetFocus(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnCadastrarLivrobtLostFocus(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnCadastrarLivroMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Livros");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/imagem/livro.png"))); // NOI18N

        javax.swing.GroupLayout pnCadastrarLivroLayout = new javax.swing.GroupLayout(pnCadastrarLivro);
        pnCadastrarLivro.setLayout(pnCadastrarLivroLayout);
        pnCadastrarLivroLayout.setHorizontalGroup(
            pnCadastrarLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadastrarLivroLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel10)
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnCadastrarLivroLayout.setVerticalGroup(
            pnCadastrarLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadastrarLivroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
            .addGroup(pnCadastrarLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 255));
        jLabel5.setText("Menu Funcionário");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Desenvolvido por:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Titione Amorim, Felipe Araujo,");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Marcelo do Nascimento, Felipe Stahlhofer");

        pnEmprestimo.setBackground(new java.awt.Color(59, 58, 149));
        pnEmprestimo.setPreferredSize(new java.awt.Dimension(187, 60));
        pnEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnEmprestimobtGetFocus(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnEmprestimobtLostFocus(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnEmprestimoMousePressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Empréstimos");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/imagem/reserva.png"))); // NOI18N

        javax.swing.GroupLayout pnEmprestimoLayout = new javax.swing.GroupLayout(pnEmprestimo);
        pnEmprestimo.setLayout(pnEmprestimoLayout);
        pnEmprestimoLayout.setHorizontalGroup(
            pnEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEmprestimoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addContainerGap())
        );
        pnEmprestimoLayout.setVerticalGroup(
            pnEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnEmprestimoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnEmprestimoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        pnRanking.setBackground(new java.awt.Color(59, 58, 149));
        pnRanking.setPreferredSize(new java.awt.Dimension(199, 60));
        pnRanking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnRankingbtGetFocus(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnRankingbtLostFocus(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnRankingMousePressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ranking da Leitura");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/imagem/ranking.png"))); // NOI18N

        javax.swing.GroupLayout pnRankingLayout = new javax.swing.GroupLayout(pnRanking);
        pnRanking.setLayout(pnRankingLayout);
        pnRankingLayout.setHorizontalGroup(
            pnRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRankingLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel15)
                .addGap(20, 20, 20)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnRankingLayout.setVerticalGroup(
            pnRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnRankingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRankingLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCadastrarLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
            .addComponent(pnRanking, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(pnEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addGap(24, 24, 24)
                .addComponent(pnEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnCadastrarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnRanking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 293, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(3, 3, 3)
                .addComponent(jLabel8)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pnCadastrarLivrobtGetFocus(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnCadastrarLivrobtGetFocus
        evt.getComponent().setBackground(new java.awt.Color(59, 50, 130));
    }//GEN-LAST:event_pnCadastrarLivrobtGetFocus

    private void pnCadastrarLivrobtLostFocus(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnCadastrarLivrobtLostFocus
        if(evt.getComponent() != panelAtivo){
            evt.getComponent().setBackground(new java.awt.Color(59, 58, 149));
        }
    }//GEN-LAST:event_pnCadastrarLivrobtLostFocus

    private void pnEmprestimobtGetFocus(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnEmprestimobtGetFocus
        evt.getComponent().setBackground(new java.awt.Color(59, 50, 130));
    }//GEN-LAST:event_pnEmprestimobtGetFocus

    private void pnEmprestimobtLostFocus(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnEmprestimobtLostFocus
        if(evt.getComponent() != panelAtivo){
            evt.getComponent().setBackground(new java.awt.Color(59, 58, 149));
        }
    }//GEN-LAST:event_pnEmprestimobtLostFocus

    private void pnRankingbtGetFocus(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnRankingbtGetFocus
        evt.getComponent().setBackground(new java.awt.Color(59, 50, 130));
    }//GEN-LAST:event_pnRankingbtGetFocus

    private void pnRankingbtLostFocus(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnRankingbtLostFocus
        if(evt.getComponent() != panelAtivo){
            evt.getComponent().setBackground(new java.awt.Color(59, 58, 149));
        }
    }//GEN-LAST:event_pnRankingbtLostFocus

    private void pnEmprestimoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnEmprestimoMousePressed
        abrirPanel(new PnEmprestimo(), evt.getComponent());
    }//GEN-LAST:event_pnEmprestimoMousePressed

    private void pnCadastrarLivroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnCadastrarLivroMousePressed
        abrirPanel(new PnCadastroLivro(), evt.getComponent());
    }//GEN-LAST:event_pnCadastrarLivroMousePressed

    private void pnRankingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnRankingMousePressed
        abrirPanel(new PnRankingLeitura(), evt.getComponent());
    }//GEN-LAST:event_pnRankingMousePressed
 
    private void abrirPanel(javax.swing.JPanel panel, java.awt.Component component){
        Principal.pnPrincipal.AbrirPanel(panel);
        ativarPanel(component);
    }
    private void ativarPanel(java.awt.Component componentPanel){
        if(panelAtivo != null){
            panelAtivo.setBackground(new java.awt.Color(59, 58, 149));
        }
        panelAtivo = componentPanel;
        panelAtivo.setBackground(new java.awt.Color(59, 50, 130));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel pnCadastrarLivro;
    private javax.swing.JPanel pnEmprestimo;
    private javax.swing.JPanel pnRanking;
    // End of variables declaration//GEN-END:variables
}
