/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view.admin;

import br.com.dao.*;
import br.com.model.*;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;

/**
 *
 * @author Felip
 */
public class PnCursoTurma extends javax.swing.JPanel {
    private Session sessao;
    private List<Curso> cursos;
    private List<Turma> turmas;
    private DefaultTableModel tabelaModelo;
    private Curso curso;
    private Turma turma;
    
    /**
     * Creates new form PnCurso
     */
    public PnCursoTurma() {
        initComponents();
        listarCurso();
        pnCursoTurma.setVisible(false);
    }
    
    private void listarCurso(){
        sessao = HibernateUtil.abrirConexao();
        CursoDao impl = new CursoDaoImpl();
        cursos = impl.listarTodos(sessao);
        sessao.close();
        DefaultListModel lista = new DefaultListModel();
        
        cursos.forEach(cu -> {
            lista.addElement(cu);
        });
        
        lsCurso.setModel(lista);
    }
    
    private void listarTurma(){
        sessao = HibernateUtil.abrirConexao();
        TurmaDao impl = new TurmaDaoImpl();
        List<Turma> turmasAux = impl.listarTodos(sessao);
        sessao.close();

        tabelaModelo = (DefaultTableModel) tbTurma.getModel();
        tabelaModelo.setNumRows(0);
        String ativo;
        
        turmas = turmasAux.stream().filter(c -> Objects.equals(c.getCurso().getId(), curso.getId())).collect(Collectors.toList());

        for (Turma tu : turmas) {          
            ativo = tu.isAberto() ? "Ativo" : "Inativo";

            tabelaModelo.addRow(new Object[]{tu.getNome(), tu.getFase(), tu.getPeriodo(),
                tu.getAno(), ativo, tu.getCurso().getNome()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        lsCurso = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        txCurso = new javax.swing.JTextField();
        btAddCurso = new javax.swing.JButton();
        pnCursoTurma = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTurma = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        pnTurma = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txNomeTurma = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txPeriodoTurma = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txAnoTurma = new javax.swing.JTextField();
        txFaseTurma = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ckAbertoTurma = new javax.swing.JCheckBox();
        btSalvarTurma = new javax.swing.JButton();
        btDeletarTurma = new javax.swing.JButton();
        txCursoSelecionado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btSalvarCurso = new javax.swing.JButton();
        btAddTurma = new javax.swing.JButton();
        btDeletarCurso = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel1.setText("Cursos / Turmas");

        lsCurso.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lsCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lsCursoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(lsCurso);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Curso");

        btAddCurso.setText("Adicionar");
        btAddCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddCursoActionPerformed(evt);
            }
        });

        tbTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Turma", "Fase", "Período", "Ano", "Ativo", "Curso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbTurma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTurmaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbTurma);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Turmas");

        pnTurma.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setText("Turma:");

        txNomeTurma.setText("jTextField2");

        jLabel7.setText("Período:");

        txPeriodoTurma.setText("jTextField2");

        jLabel6.setText("Ano:");

        txAnoTurma.setText("jTextField2");

        txFaseTurma.setText("jTextField2");

        jLabel5.setText("Fase:");

        ckAbertoTurma.setBackground(new java.awt.Color(204, 204, 204));
        ckAbertoTurma.setText("Ativo");

        btSalvarTurma.setText("Salvar");
        btSalvarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarTurmaActionPerformed(evt);
            }
        });

        btDeletarTurma.setText("Deletar");
        btDeletarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarTurmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTurmaLayout = new javax.swing.GroupLayout(pnTurma);
        pnTurma.setLayout(pnTurmaLayout);
        pnTurmaLayout.setHorizontalGroup(
            pnTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTurmaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTurmaLayout.createSequentialGroup()
                        .addGroup(pnTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txPeriodoTurma))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnTurmaLayout.createSequentialGroup()
                                .addComponent(txAnoTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btDeletarTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btSalvarTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)))
                    .addGroup(pnTurmaLayout.createSequentialGroup()
                        .addGroup(pnTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnTurmaLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txNomeTurma, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txFaseTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ckAbertoTurma)))
                .addContainerGap())
        );
        pnTurmaLayout.setVerticalGroup(
            pnTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTurmaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnTurmaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txNomeTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnTurmaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txFaseTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ckAbertoTurma))
                .addGroup(pnTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTurmaLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pnTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btSalvarTurma)
                            .addComponent(btDeletarTurma)))
                    .addGroup(pnTurmaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnTurmaLayout.createSequentialGroup()
                                .addGroup(pnTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txPeriodoTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txAnoTurma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        txCursoSelecionado.setText("jTextField1");

        jLabel8.setText("Curso Selecionado:");

        btSalvarCurso.setText("Salvar Edição");
        btSalvarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarCursoActionPerformed(evt);
            }
        });

        btAddTurma.setText("Adicionar Nova Turma");
        btAddTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddTurmaActionPerformed(evt);
            }
        });

        btDeletarCurso.setText("Deletar");
        btDeletarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCursoTurmaLayout = new javax.swing.GroupLayout(pnCursoTurma);
        pnCursoTurma.setLayout(pnCursoTurmaLayout);
        pnCursoTurmaLayout.setHorizontalGroup(
            pnCursoTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCursoTurmaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnCursoTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCursoTurmaLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCursoTurmaLayout.createSequentialGroup()
                        .addGroup(pnCursoTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnCursoTurmaLayout.createSequentialGroup()
                                .addComponent(txCursoSelecionado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btDeletarCurso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btSalvarCurso))
                            .addComponent(pnTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnCursoTurmaLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btAddTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21))))
        );
        pnCursoTurmaLayout.setVerticalGroup(
            pnCursoTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCursoTurmaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCursoTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txCursoSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSalvarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDeletarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAddTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txCurso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btAddCurso))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addComponent(pnCursoTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1))
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAddCurso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(pnCursoTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAddTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddTurmaActionPerformed
        turma = new Turma();
        turma.setCurso(curso);
        preencherTurma();
    }//GEN-LAST:event_btAddTurmaActionPerformed

    private void btAddCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddCursoActionPerformed
        if(txCurso.getText().trim().isEmpty()){
            return;
        }
        sessao = HibernateUtil.abrirConexao();
        CursoDao impl = new CursoDaoImpl();
        Curso newCurso = new Curso(null, txCurso.getText());
        impl.salvarOuAlterar(newCurso, sessao);
        sessao.close();
        listarCurso();
    }//GEN-LAST:event_btAddCursoActionPerformed

    private void btSalvarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarCursoActionPerformed
        sessao = HibernateUtil.abrirConexao();
        CursoDao impl = new CursoDaoImpl();
        curso.setNome(txCursoSelecionado.getText());
        impl.salvarOuAlterar(curso, sessao);
        sessao.close();
        listarCurso();
    }//GEN-LAST:event_btSalvarCursoActionPerformed

    private void tbTurmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTurmaMouseClicked
        turma = turmas.get(tbTurma.getSelectedRow());
        preencherTurma();
    }//GEN-LAST:event_tbTurmaMouseClicked

    private void btDeletarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDeletarCursoActionPerformed

    private void btSalvarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarTurmaActionPerformed
        sessao = HibernateUtil.abrirConexao();
        TurmaDao impl = new TurmaDaoImpl();
        turma.setNome(txCursoSelecionado.getText());
        turma.setNome(txNomeTurma.getText());
        turma.setFase(txFaseTurma.getText());
        turma.setAno(txAnoTurma.getText());
        turma.setPeriodo(txPeriodoTurma.getText());
        turma.setAberto(ckAbertoTurma.isSelected());
        impl.salvarOuAlterar(turma, sessao);
        sessao.close();
        listarTurma();
    }//GEN-LAST:event_btSalvarTurmaActionPerformed

    private void btDeletarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarTurmaActionPerformed
         sessao = HibernateUtil.abrirConexao();
        TurmaDao impl = new TurmaDaoImpl();
        impl.excluir(turma, sessao);
        sessao.close();
    }//GEN-LAST:event_btDeletarTurmaActionPerformed

    private void lsCursoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lsCursoMousePressed
        pnTurma.setVisible(false);
        DefaultListModel aa = (DefaultListModel) this.lsCurso.getModel();
        curso = (Curso)aa.get(lsCurso.getSelectedIndex());
        txCursoSelecionado.setText(curso.getNome());
        listarTurma();
        if(!pnCursoTurma.isVisible())
            pnCursoTurma.setVisible(true); 
    }//GEN-LAST:event_lsCursoMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddCurso;
    private javax.swing.JButton btAddTurma;
    private javax.swing.JButton btDeletarCurso;
    private javax.swing.JButton btDeletarTurma;
    private javax.swing.JButton btSalvarCurso;
    private javax.swing.JButton btSalvarTurma;
    private javax.swing.JCheckBox ckAbertoTurma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList<String> lsCurso;
    private javax.swing.JPanel pnCursoTurma;
    private javax.swing.JPanel pnTurma;
    private javax.swing.JTable tbTurma;
    private javax.swing.JTextField txAnoTurma;
    private javax.swing.JTextField txCurso;
    private javax.swing.JTextField txCursoSelecionado;
    private javax.swing.JTextField txFaseTurma;
    private javax.swing.JTextField txNomeTurma;
    private javax.swing.JTextField txPeriodoTurma;
    // End of variables declaration//GEN-END:variables

    private void preencherTurma() {
        if(!pnTurma.isVisible())
            pnTurma.setVisible(true);
        
        txNomeTurma.setText(turma.getNome());
        txFaseTurma.setText(turma.getFase());
        txAnoTurma.setText(turma.getAno());
        ckAbertoTurma.setSelected(turma.isAberto());
        txPeriodoTurma.setText(turma.getPeriodo());
    }
}
