/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view.funcionario;

import br.com.dao.*;
import br.com.model.*;
import br.com.view.Principal;
import javax.swing.JOptionPane;
import org.hibernate.Session;

/**
 *
 * @author Marcelo
 */
public class PnCadastrarLivro extends javax.swing.JPanel {

    private Session sessao;
    private Livro livro;
    private Exemplar exemplar;
    private LivroDao livroDao;
    private ExemplarDao exemplarDao;

    public PnCadastrarLivro(Livro livro) {
        initComponents();
        this.livro = livro;
        livroDao = new LivroDaoImpl();
        exemplarDao = new ExemplarDaoImpl();
    }

    public PnCadastrarLivro(Exemplar exemplar) {
        initComponents();

        this.livro = livro;
        livroDao = new LivroDaoImpl();
        tfTitulo.setText(exemplar.getLivro().getTitulo());
        tfAutor.setText(exemplar.getLivro().getAutor());
        tfEditora.setText(exemplar.getLivro().getEditora());
        tfEdicao.setText(exemplar.getLivro().getEdicao());
        tfIsbn.setText(exemplar.getLivro().getIsbn());

        this.exemplar = exemplar;
        exemplarDao = new ExemplarDaoImpl();
        tfCodigoLivro.setText(exemplar.getCodigoLivro());

        btSalvar.setText("Alterar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfTitulo = new javax.swing.JTextField();
        txAutor = new javax.swing.JLabel();
        tfAutor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfEdicao = new javax.swing.JTextField();
        tfEditora = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfIsbn = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfCodigoLivro = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setAutoscrolls(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel1.setText("Cadastrar Livro");

        jLabel3.setText("Título");

        txAutor.setText("Autor");

        jLabel6.setText("Editora");

        jLabel5.setText("Edição");

        jLabel7.setText("ISBN");

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        jLabel2.setText("Código");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txAutor))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfEdicao, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                    .addComponent(jLabel5)))
                            .addComponent(tfAutor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTitulo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(tfIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tfCodigoLivro)
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCodigoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        limpar();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

        try {
            if (btSalvar.getText() == "Alterar") {
                sessao = HibernateUtil.abrirConexao();
                livro = exemplar.getLivro();
                livro.setTitulo(tfTitulo.getText());;
                livro.setAutor(tfAutor.getText());
                livro.setEditora(tfEditora.getText());
                livro.setEdicao(tfEdicao.getText());
                livro.setIsbn(tfIsbn.getText());
                exemplar.setCodigoLivro(tfCodigoLivro.getText());
                exemplar.setLivro(livro);                

                livroDao.salvarOuAlterar(livro, sessao);
                exemplarDao.salvarOuAlterar(exemplar, sessao);
                
                JOptionPane.showMessageDialog(null, "Livro alterado com sucesso!");
            } else {
                sessao = HibernateUtil.abrirConexao();
                ExemplarDao exemplarImpl = new ExemplarDaoImpl();
                LivroDao livroImpl = new LivroDaoImpl();
                livro = new Livro();
                livro.setTitulo(tfTitulo.getText());;
                livro.setAutor(tfAutor.getText());
                livro.setEditora(tfEditora.getText());
                livro.setEdicao(tfEdicao.getText());
                livro.setIsbn(tfIsbn.getText());
                exemplar = new Exemplar();
                exemplar.setCodigoLivro(tfCodigoLivro.getText());
                exemplar.setStatus(true);
                exemplar.setLivro(livro);
                livroDao.salvarOuAlterar(livro, sessao);
                exemplarDao.salvarOuAlterar(exemplar, sessao);
                JOptionPane.showMessageDialog(null, "Livro salvo com sucesso!");
            }
        } catch (Exception e) {
            System.out.println("Erro a salvar Livro - Causa: " + e);
            JOptionPane.showMessageDialog(null, "Erro ao salvar livro, comunique o administrador do sistema!\n\n\n Informe sobre o erro: " + e);
        } finally {
            sessao.close();
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        Principal.pnPrincipal.AbrirPanel(new PnLivro());
    }//GEN-LAST:event_btVoltarActionPerformed

    private boolean validarCampo() {
        String mensagem = "";
        boolean erro = false;

        String tituloLivro = tfTitulo.getText().trim();
        if (tituloLivro.length() <= 2) {
            mensagem += "Valor inválido para o Título!";
            erro = true;
        }

        String autorLivro = tfAutor.getText().trim();
        if (autorLivro.length() <= 3) {
            mensagem += "\nValor inválido para Autor!";
            erro = true;
        }

        String editoraLivro = tfEditora.getText().trim();
        if (editoraLivro.length() <= 2) {
            mensagem += "\nValor inválido para o Editora!";
            erro = true;
        }

        String isbnLivro = tfIsbn.getText().trim();
        if (isbnLivro.length() != 13) {
            mensagem += "\nValor inválido para ISBN!";
            erro = true;
        }

        String codigoLivro = tfCodigoLivro.getText().trim();
        if (codigoLivro.length() < 5) {
            mensagem += "\nValor inválido para Código do Livro!";
            erro = true;
        }

        if (erro) {
            JOptionPane.showMessageDialog(null, mensagem);
        }
        return erro;
    }

    private void limpar() {
        tfTitulo.setText("");
        tfAutor.setText("");
        tfEdicao.setText("");
        tfEditora.setText("");
        tfIsbn.setText("");
        tfCodigoLivro.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField tfAutor;
    private javax.swing.JTextField tfCodigoLivro;
    private javax.swing.JTextField tfEdicao;
    private javax.swing.JTextField tfEditora;
    private javax.swing.JTextField tfIsbn;
    private javax.swing.JTextField tfTitulo;
    private javax.swing.JLabel txAutor;
    // End of variables declaration//GEN-END:variables
}
